import { DEFAULT_TEAM_ID, DEFAULT_TYLOO_ROSTER, LEGACY_DEV_SQUAD } from "@tyloo/shared";

export const DEFAULT_SQUAD = DEFAULT_TYLOO_ROSTER;

export { DEFAULT_TEAM_ID, DEFAULT_TYLOO_ROSTER, LEGACY_DEV_SQUAD };
